#===============================================================================
# Copyright 2014-2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#===============================================================================

##  Content:
##     Intel(R) Data Analytics Acceleration Library algorithms list
##******************************************************************************

naivebayes += classifier
svm += classifier kernel_function
em += covariance
adaboost += boosting weak_learner
weak_learner += stump
neural_networks/layers += neural_networks/initializers/uniform
neural_networks/layers/fullyconnected_layer += neural_networks/layers/fullyconnected_layer/backward \
                                               neural_networks/layers/fullyconnected_layer/forward  \
                                               neural_networks/layers/loss_layer                    \
                                               neural_networks/layers
neural_networks/layers/loss_layer/softmax_cross_layer += neural_networks/layers/loss_layer/softmax_cross_layer/backward \
                                                         neural_networks/layers/loss_layer/softmax_cross_layer/forward  \
                                                         neural_networks/layers/loss_layer                              \
                                                         neural_networks/layers                                         \
                                                         neural_networks/layers/softmax_layer/forward                   \
                                                         neural_networks/layers/softmax_layer/backward                  \
                                                         neural_networks/layers/softmax_layer
neural_networks += neural_networks/layers objective_function optimization_solver optimization_solver/sgd neural_networks/layers/loss_layer
k_nearest_neighbors += classifier
decision_tree += classifier regression
linear_model += regression
linear_regression += linear_model
ridge_regression += linear_model

CORE.ALGORITHMS.FULL :=                                                       \
    covariance                                                                \
    implicit_als                                                              \
    kmeans                                                                    \
    low_order_moments                                                         \
    linear_model                                                              \
    classifier                                                                \
    regression                                                                \
    linear_regression                                                         \
    ridge_regression                                                          \
    objective_function                                                        \
    objective_function/mse                                                    \
    optimization_solver                                                       \
    optimization_solver/sgd                                                   \
    optimization_solver/lbfgs                                                 \
    optimization_solver/adagrad                                               \
    naivebayes                                                                \
    neural_networks                                                           \
    neural_networks/initializers                                              \
    neural_networks/initializers/uniform                                      \
    neural_networks/initializers/xavier                                       \
    neural_networks/initializers/gaussian                                     \
    neural_networks/initializers/truncated_gaussian                           \
    neural_networks/layers                                                    \
    neural_networks/layers/abs_layer                                          \
    neural_networks/layers/abs_layer/backward                                 \
    neural_networks/layers/abs_layer/forward                                  \
    neural_networks/layers/batch_normalization_layer                          \
    neural_networks/layers/batch_normalization_layer/backward                 \
    neural_networks/layers/batch_normalization_layer/forward                  \
    neural_networks/layers/concat_layer                                       \
    neural_networks/layers/concat_layer/backward                              \
    neural_networks/layers/concat_layer/forward                               \
    neural_networks/layers/convolution2d_layer                                \
    neural_networks/layers/convolution2d_layer/backward                       \
    neural_networks/layers/convolution2d_layer/forward                        \
    neural_networks/layers/dropout_layer                                      \
    neural_networks/layers/dropout_layer/backward                             \
    neural_networks/layers/dropout_layer/forward                              \
    neural_networks/layers/fullyconnected_layer                               \
    neural_networks/layers/fullyconnected_layer/backward                      \
    neural_networks/layers/fullyconnected_layer/forward                       \
    neural_networks/layers/lcn_layer                                          \
    neural_networks/layers/lcn_layer/backward                                 \
    neural_networks/layers/lcn_layer/forward                                  \
    neural_networks/layers/locallyconnected2d_layer                           \
    neural_networks/layers/locallyconnected2d_layer/backward                  \
    neural_networks/layers/locallyconnected2d_layer/forward                   \
    neural_networks/layers/logistic_layer                                     \
    neural_networks/layers/logistic_layer/backward                            \
    neural_networks/layers/logistic_layer/forward                             \
    neural_networks/layers/reshape_layer                                      \
    neural_networks/layers/reshape_layer/backward                             \
    neural_networks/layers/reshape_layer/forward                              \
    neural_networks/layers/lrn_layer                                          \
    neural_networks/layers/lrn_layer/backward                                 \
    neural_networks/layers/lrn_layer/forward                                  \
    neural_networks/layers/pooling1d_layer                                    \
    neural_networks/layers/pooling1d_layer/backward                           \
    neural_networks/layers/pooling1d_layer/forward                            \
    neural_networks/layers/pooling2d_layer                                    \
    neural_networks/layers/pooling2d_layer/backward                           \
    neural_networks/layers/pooling2d_layer/forward                            \
    neural_networks/layers/pooling3d_layer                                    \
    neural_networks/layers/pooling3d_layer/backward                           \
    neural_networks/layers/pooling3d_layer/forward                            \
    neural_networks/layers/spatial_pooling2d_layer                            \
    neural_networks/layers/spatial_pooling2d_layer/backward                   \
    neural_networks/layers/spatial_pooling2d_layer/forward                    \
    neural_networks/layers/prelu_layer                                        \
    neural_networks/layers/prelu_layer/backward                               \
    neural_networks/layers/prelu_layer/forward                                \
    neural_networks/layers/relu_layer                                         \
    neural_networks/layers/relu_layer/backward                                \
    neural_networks/layers/relu_layer/forward                                 \
    neural_networks/layers/smoothrelu_layer                                   \
    neural_networks/layers/smoothrelu_layer/backward                          \
    neural_networks/layers/smoothrelu_layer/forward                           \
    neural_networks/layers/loss_layer                                         \
    neural_networks/layers/loss_layer/logistic_cross_layer                    \
    neural_networks/layers/loss_layer/logistic_cross_layer/backward           \
    neural_networks/layers/loss_layer/logistic_cross_layer/forward            \
    neural_networks/layers/loss_layer/softmax_cross_layer                     \
    neural_networks/layers/loss_layer/softmax_cross_layer/backward            \
    neural_networks/layers/loss_layer/softmax_cross_layer/forward             \
    neural_networks/layers/softmax_layer                                      \
    neural_networks/layers/softmax_layer/backward                             \
    neural_networks/layers/softmax_layer/forward                              \
    neural_networks/layers/split_layer                                        \
    neural_networks/layers/split_layer/backward                               \
    neural_networks/layers/split_layer/forward                                \
    neural_networks/layers/tanh_layer                                         \
    neural_networks/layers/tanh_layer/backward                                \
    neural_networks/layers/tanh_layer/forward                                 \
    neural_networks/layers/transposed_conv2d_layer                            \
    neural_networks/layers/transposed_conv2d_layer/backward                   \
    neural_networks/layers/transposed_conv2d_layer/forward                    \
    pca                                                                       \
    qr                                                                        \
    svd                                                                       \
    mf_sgd														  


CORE.ALGORITHMS := $(if $(CORE.ALGORITHMS.CUSTOM), $(CORE.ALGORITHMS.CUSTOM), $(CORE.ALGORITHMS.FULL))
CORE.ALGORITHMS := $(sort $(foreach alg,$(CORE.ALGORITHMS),$(foreach alg1,$($(alg)),$($(alg1)) $(alg1)) $(alg)))

CORE.ALGORITHMS.INC :=                                                        \
    covariance                                                                \
    implicit_als                                                              \
    kmeans                                                                    \
    linear_model                                                              \
    classifier                                                                \
    moments                                                                   \
    naive_bayes                                                               \
    regression                                                                \
    linear_regression                                                         \
    ridge_regression                                                          \
    optimization_solver                                                       \
    optimization_solver/adagrad                                               \
    optimization_solver/iterative_solver                                      \
    optimization_solver/lbfgs                                                 \
    optimization_solver/objective_function                                    \
    optimization_solver/precomputed                                           \
    optimization_solver/sgd                                                   \
    neural_networks                                                           \
    neural_networks/initializers                                              \
    neural_networks/initializers/gaussian                                     \
    neural_networks/initializers/truncated_gaussian                           \
    neural_networks/initializers/uniform                                      \
    neural_networks/initializers/xavier                                       \
    neural_networks/layers                                                    \
    neural_networks/layers/abs                                                \
    neural_networks/layers/batch_normalization                                \
    neural_networks/layers/concat                                             \
    neural_networks/layers/convolution2d                                      \
    neural_networks/layers/dropout                                            \
    neural_networks/layers/fullyconnected                                     \
    neural_networks/layers/lcn                                                \
    neural_networks/layers/locallyconnected2d                                 \
    neural_networks/layers/logistic                                           \
    neural_networks/layers/loss                                               \
    neural_networks/layers/lrn                                                \
    neural_networks/layers/pooling1d                                          \
    neural_networks/layers/pooling2d                                          \
    neural_networks/layers/pooling3d                                          \
    neural_networks/layers/prelu                                              \
    neural_networks/layers/relu                                               \
    neural_networks/layers/reshape                                            \
    neural_networks/layers/smoothrelu                                         \
    neural_networks/layers/softmax                                            \
    neural_networks/layers/spatial_pooling2d                                  \
    neural_networks/layers/split                                              \
    neural_networks/layers/tanh                                               \
    neural_networks/layers/transposed_conv2d                                  \
    pca                                                                       \
    qr                                                                        \
    svd                                                                       \
	mf_sgd													 


CORE.SERVICES       := compression            \
                       data_management

JJ.ALGORITHMS       :=                                                           \
                       covariance                                                \
                       implicit_als                                              \
                       implicit_als/prediction                                   \
                       implicit_als/prediction/ratings                           \
                       implicit_als/training                                     \
                       implicit_als/training/init                                \
                       classifier                                                \
                       classifier/prediction                                     \
                       classifier/quality_metric                                 \
                       classifier/quality_metric/binary_confusion_matrix         \
                       classifier/quality_metric/multi_class_confusion_matrix    \
                       classifier/training                                       \
                       kmeans                                                    \
                       kmeans/init                                               \
                       quality_metric                                            \
                       quality_metric_set                                        \
                       low_order_moments                                         \
                       optimization_solver                                       \
                       optimization_solver/objective_function                    \
                       optimization_solver/sum_of_functions                      \
                       optimization_solver/mse                                   \
                       optimization_solver/precomputed                           \
                       optimization_solver/iterative_solver                      \
                       optimization_solver/sgd                                   \
                       optimization_solver/lbfgs                                 \
                       optimization_solver/adagrad                               \
                       linear_regression                                         \
                       linear_regression/prediction                              \
                       linear_regression/quality_metric                          \
                       linear_regression/quality_metric_set                      \
                       linear_regression/training                                \
                       ridge_regression                                          \
                       ridge_regression/prediction                               \
                       ridge_regression/training                                 \
                       multinomial_naive_bayes                                   \
                       multinomial_naive_bayes/prediction                        \
                       multinomial_naive_bayes/quality_metric_set                \
                       multinomial_naive_bayes/training                          \
                       neural_networks                                           \
                       neural_networks/initializers                              \
                       neural_networks/initializers/uniform                      \
                       neural_networks/initializers/xavier                       \
                       neural_networks/initializers/gaussian                     \
                       neural_networks/initializers/truncated_gaussian           \
                       neural_networks/layers                                    \
                       neural_networks/layers/abs                                \
                       neural_networks/layers/average_pooling1d                  \
                       neural_networks/layers/average_pooling2d                  \
                       neural_networks/layers/average_pooling3d                  \
                       neural_networks/layers/batch_normalization                \
                       neural_networks/layers/concat                             \
                       neural_networks/layers/convolution2d                      \
                       neural_networks/layers/transposed_conv2d                  \
                       neural_networks/layers/dropout                            \
                       neural_networks/layers/fullyconnected                     \
                       neural_networks/layers/logistic                           \
                       neural_networks/layers/loss                               \
                       neural_networks/layers/lrn                                \
                       neural_networks/layers/maximum_pooling1d                  \
                       neural_networks/layers/maximum_pooling2d                  \
                       neural_networks/layers/maximum_pooling3d                  \
                       neural_networks/layers/reshape                            \
                       neural_networks/layers/stochastic_pooling2d               \
                       neural_networks/layers/spatial_pooling2d                  \
                       neural_networks/layers/spatial_average_pooling2d          \
                       neural_networks/layers/spatial_maximum_pooling2d          \
                       neural_networks/layers/spatial_stochastic_pooling2d       \
                       neural_networks/layers/pooling1d                          \
                       neural_networks/layers/pooling2d                          \
                       neural_networks/layers/pooling3d                          \
                       neural_networks/layers/prelu                              \
                       neural_networks/layers/relu                               \
                       neural_networks/layers/logistic_cross                     \
                       neural_networks/layers/smoothrelu                         \
                       neural_networks/layers/softmax                            \
                       neural_networks/layers/softmax_cross                      \
                       neural_networks/layers/split                              \
                       neural_networks/layers/tanh                               \
                       neural_networks/layers/lcn                                \
                       neural_networks/layers/locallyconnected2d                 \
                       neural_networks/prediction                                \
                       neural_networks/training                                  \
                       pca                                                       \
                       qr                                                        \
                       svd                                                       \
                       mf_sgd
                       

JJ.DATA_MANAGEMENT  := data                                                      \
                       data_source                                               \
                       compression                                               \
                       compression/bzip2                                         \
                       compression/lzo                                           \
                       compression/rle                                           \
                       compression/zlib

JJ.SERVICES         := libraryversioninfo
