#===============================================================================
# Copyright 2014-2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#===============================================================================

##  Content:
##     Intel(R) Data Analytics Acceleration Library algorithms list
##******************************************************************************

naivebayes += classifier
svm += classifier kernel_function
em += covariance
adaboost += boosting weak_learner
weak_learner += stump
neural_networks/layers += neural_networks/initializers/uniform
neural_networks/layers/fullyconnected_layer += neural_networks/layers/fullyconnected_layer/backward \
                                               neural_networks/layers/fullyconnected_layer/forward  \
                                               neural_networks/layers/loss_layer                    \
                                               neural_networks/layers
neural_networks/layers/loss_layer/softmax_cross_layer += neural_networks/layers/loss_layer/softmax_cross_layer/backward \
                                                         neural_networks/layers/loss_layer/softmax_cross_layer/forward  \
                                                         neural_networks/layers/loss_layer                              \
                                                         neural_networks/layers                                         \
                                                         neural_networks/layers/softmax_layer/forward                   \
                                                         neural_networks/layers/softmax_layer/backward                  \
                                                         neural_networks/layers/softmax_layer
neural_networks += neural_networks/layers objective_function optimization_solver optimization_solver/sgd neural_networks/layers/loss_layer
k_nearest_neighbors += classifier
decision_tree += classifier regression
linear_model += regression
linear_regression += linear_model
ridge_regression += linear_model

CORE.ALGORITHMS.FULL :=                                                       \
    covariance                                                                \
    subgraph																  \
	mf_sgd


CORE.ALGORITHMS := $(if $(CORE.ALGORITHMS.CUSTOM), $(CORE.ALGORITHMS.CUSTOM), $(CORE.ALGORITHMS.FULL))
CORE.ALGORITHMS := $(sort $(foreach alg,$(CORE.ALGORITHMS),$(foreach alg1,$($(alg)),$($(alg1)) $(alg1)) $(alg)))

CORE.ALGORITHMS.INC :=                                                        \
    covariance                                                                \
    subgraph																  \
	mf_sgd

    
CORE.SERVICES       := compression            \
                       data_management

JJ.ALGORITHMS       :=                                                           \
                       covariance                                                \
                       subgraph													 \
					   mf_sgd
                                              

JJ.DATA_MANAGEMENT  := data                                                      \
                       data_source                                               \
                       compression                                               \
                       compression/bzip2                                         \
                       compression/lzo                                           \
                       compression/rle                                           \
                       compression/zlib

JJ.SERVICES         := libraryversioninfo
